[package]
name = "intel-hfi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitfield-struct = "0.10.1"
clap = { version = "4.5.31", features = ["derive"] }
